
version: "3.8"
services:
  caddy:
    image: caddy:2.8
    container_name: aurebix-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  caddy_data:
  caddy_config:
