name: Mobile Audit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Mobile Audit
        run: bun run audit:mobile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-audit
          path: |
            audit/mobile-audit.json
            audit/mobile-audit.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const md = fs.readFileSync('audit/mobile-audit.md','utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### 📱 Mobile Audit Report\n\n${md}`
            });
